### ISSUE TITLE
Arrumar os problemas de thread:

### ISSUE THREAD

**Issue by SampaioFelipe** [secompufscar/app_secompufscar#1]
- Instância em várias threads
- NullPointer Exception

**Comment by sugayaa** [comment]
Beleza

Em 14/06/2017 13:23, "Felipe Sampaio" <notifications@github.com> escreveu:

**Comment by olivatooo** [comment]
Branch com a issue já criada e em atual correção.

**Comment by olivatooo** [comment]
Arrumado
