### ISSUE TITLE
Encontrar novas issues no app

### ISSUE THREAD

**Issue by olivatooo** [secompufscar/app_secompufscar#49]
* Testar todo o app
* Gerar novas ideias

**Comment by MFelipe96** [comment]
- Sugestão para o app
	1. As notícias da "HOME" poderiam ser organizadas com marcadores.
		- Ajudaria na visualização do participante por estarem organizadas e destacadas.
        2. Na página do "Cronograma" poderia aparecer um breve resumo do evento que irá acontecer ao clicar no evento e uma forma de favoritar os eventos que o participante tem mais interesse.

Obs: Algumas abas ainda não estão preenchidas, o que acabou por limitar as sugestões.

**Comment by olivatooo** [comment]
`Na página do "Cronograma" poderia aparecer um breve resumo do evento que irá acontecer ao clicar no evento e uma forma de favoritar os eventos que o participante tem mais interesse.`
Isso nosso app já possui,mas como não temos um cronograma ainda, não é possível fazer isso
